### ISSUE TITLE
TypeError: Cannot read property "'UALs'" of undefined

### ISSUE THREAD

**Issue by haroldboom** [Aescwine/otnode-tester#1]
Hey mate,

I installed all the dependicies but I am getting this error over and over

"TypeError: Cannot read property "'UALs'" of undefined
![Screenshot 2022-03-16 200855](https://user-images.githubusercontent.com/42967743/158555520-e4edf021-97de-43cd-8e34-0ed930606027.png)
"

see attached. Thanks!

**Comment by Aescwine** [comment]
Hey, I've just pushed an update that should fix this as others were getting the same issue. It's due to what I think is a bug in otnode. It's because your node hasn't finished publishing the data. Anyway, I've added a hack to get it working if the status is PENDING. Cheers!

**Comment by haroldboom** [comment]
Awesome thanks mate!
